name: Sync to Cloudflare R2 (API)

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Checkout Repository
        uses: actions/checkout@v4

      - name: 📤 Upload Files to Cloudflare R2
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          BUCKET_NAME: "meer"
        run: |
          for file in $(find . -type f ! -path "./.git/*"); do
            file_path=$(echo $file | sed 's|^\./||')  # Remove ./ from path
            echo "Uploading $file_path to R2..."

            curl -X PUT "https://$CLOUDFLARE_ACCOUNT_ID.r2.cloudflarestorage.com/$BUCKET_NAME/$file_path" \
              -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
              -H "Content-Type: application/octet-stream" \
              --data-binary "@$file"
          done
