name: Sync to Cloudflare R2

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Checkout Repository (with Auth)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: 📤 Upload Files to Cloudflare R2
        env:
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_KEY: ${{ secrets.R2_ACCESS_KEY }}
          R2_SECRET_KEY: ${{ secrets.R2_SECRET_KEY }}
          BUCKET_NAME: "meer"
        run: |
          for file in $(find . -type f); do
            curl -X PUT "https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com/${BUCKET_NAME}/${file}" \
              -H "Authorization: AWS ${R2_ACCESS_KEY}:${R2_SECRET_KEY}" \
              --data-binary "@${file}"
          done
