name: Sync to Cloudflare R2

on:
  push:  # Runs ONLY on push to the repo
    branches:
      - main  # Change if you want to sync other branches

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Checkout Repository
        uses: actions/checkout@v4

      - name: ⬆ Upload Files to Cloudflare R2
        env:
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_KEY: ${{ secrets.R2_ACCESS_KEY }}
          R2_SECRET_KEY: ${{ secrets.R2_SECRET_KEY }}
          BUCKET_NAME: "my-github-files"  # Change to your R2 bucket name
        run: |
          for file in $(find . -type f); do
            curl -X PUT "https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com/${BUCKET_NAME}/${file}" \
              -H "Authorization: AWS ${R2_ACCESS_KEY}:${R2_SECRET_KEY}" \
              --data-binary "@${file}"
          done
